# Generated by Django 3.2.13 on 2022-06-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='user',
        ),
    ]
