# Generated by Django 3.2.13 on 2022-06-18 14:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_author_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
